site_name: Invariant Testing
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.svg
  features:
    - content.code.copy
extra_css:
  - assets/invariant.css
use_directory_urls: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences