name: Documentation Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: docs
      run: docker build . --tag testing-docs:main
    - name: Login to Invariant Container Registry
      run: echo ${{ secrets.INVARIANT_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.INVARIANT_REGISTRY_USERNAME }} --password-stdin https://images.invariantnet.com
    - name: Rename the Docker image
      run: docker tag testing-docs:main images.invariantnet.com/testing-docs:main
    - name: Push the Docker image
      run: docker push images.invariantnet.com/testing-docs:main